### ISSUE TITLE
CMK Pusher send wrong time

### ISSUE THREAD

**Issue by Luca65ZZ** [qmexnetworks/cmk-pusher-agent#1]
Hi, I'm starting to use cmk pusher on four test windows 7 and 10 machines and on all of them I have the same problem: inside the file cmk pusher send to nagios server, the hour is wrong.
There is a difference of 2 hours between the real time and the time inside the "machine status" file.
For example: on a machine with time 9.00 AM with right time get from NTP, the time inside the file sent by cmk pusher is 7.00 AM. Please, take note the server have right time sync with NTP, the same as Windows client machine.
Please, may you help me to correct this issue?
Thanks in advance
LUCA (Italy)

**Comment by qmex-mp** [comment]
Hi,
iam happy to correct this as soon I can understand it.
Are there different Time Zones on Server and Client?

**Comment by Luca65ZZ** [comment]
Hi, many thanks for reply.
There arent differences between server and client, are both in the same Time Zone.
When the client put info on server, I can see, inside the "dump" file on server, a wrong time, with a delay of two hours. I set on client and server the same NTP server to be sure to have the same date and time and this setting is working fine. I really dont understand why the time is right on both but inside the "dump" file on server I get two hour less.
Thanks for your help
LUCA

**Comment by Luca65ZZ** [comment]
There is an additional problem regarding date and time: today, 19 october 2018, I can see on host monitored through cmkpusher this check:
![datetimeerror](https://user-images.githubusercontent.com/33755276/47212164-b7aeaa80-d397-11e8-9a76-30c4a3651fbf.jpg)
It seems there is an issue calculating right time and date.
Please, do you have a solution for this?
Thanks
LUCA

**Comment by Luca65ZZ** [comment]
Hi qmex-mp, please may you check for this problem?
If not, no problems, I can join a different solution ;-)
many thanks
LUCA

**Comment by Luca65ZZ** [comment]
The problem should be in the file json.php in the line "$content .= "last_connect ".date("Y-m-d H:i:s")."\n";"
I suppose here the software get UTC time instead of real time based on current Time Zone.
Another problem should be the "-" as date separator (see my post of 10 days ago where Check_MK gives me only 322 seconds but the real time is 9 days before! (October 10 instead of October 19!)
What can I do to solve this problem and get the right time on my Check_MK server?
thanks
LUCA

**Comment by Luca65ZZ** [comment]
Good news! Problem partially solved: I add the following line to json.php:
"date_default_timezone_set('Europe/Rome');"
With this line the system gets the right date and time and write it inside the "dump" file.
I still need to solve the calc of date ... it's still wrong.

**Comment by qmex-mp** [comment]
Hi,
this explains why i couldnt replicate the issue.
Its not necessary to set the timezone in the PHP File, you should set the correct timezone in your php.ini thats the best solution.

As for the other thing:
I will rewrite the whole time calculation code in the check_mk check new, this week.

**Comment by qmex-mp** [comment]
Can you do me a favor an get me the result of "date" on your check_mk servers CLI?

**Comment by Luca65ZZ** [comment]
Many thanks! ;-)

I put “date” command in the ssh console of check_mk server and the result is:

Wed Oct 31 17:34:33 CET 2018

Bye

LUCA

 

Da: qmex-mp <notifications@github.com> 
Inviato: lunedì 29 ottobre 2018 18:33
A: qmexnetworks/cmk-pusher-agent <cmk-pusher-agent@noreply.github.com>
Cc: Luca65ZZ <luca.lazzaroni@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [qmexnetworks/cmk-pusher-agent] CMK Pusher send wrong time (#1)

 

Hi,
this explains why i couldnt replicate the issue.
Its not necessary to set the timezone in the PHP File, you should set the correct timezone in your php.ini thats the best solution.

As for the other thing:
I will rewrite the whole time calculation code in the check_mk check new, this week.

**Comment by qmex-mp** [comment]
Hi, 
thanks for the data (this was only to confirm correct timezone configuration.
Its now fixed and you only have to exchange the check_mk check for the new one.

**Comment by Luca65ZZ** [comment]
Many thanks again! ;-)
It seems all is working fine now :-)
Ciao!
LUCA
